apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: coredumpquotas.coredump.k8s.io
spec:
  group: coredump.k8s.io
  names:
    kind: CoredumpQuota
    listKind: CoredumpQuotaList
    plural: coredumpquotas
    singular: coredumpquota
  scope: Namespaced
  version: v1alpha1


---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: coredumps.coredump.k8s.io
spec:
  group: coredump.k8s.io
  names:
    kind: Coredump
    listKind: CoredumpList
    plural: coredumps
    singular: coredump
  scope: Namespaced
    # subresources describes the subresources for custom resources.
  subresources:
    # status enables the status subresource.
    status: {}
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ContainerName:
              type: string
            Pod:
              type: string
            Pid:
              type: integer
              minimum: 0
            Filename:
              type: string
            Time:
              type: dateTime
            Volume:
              type: string
