#rbac settings for service account system:serviceaccount:kube-system:default
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: 'system:coredump-detector'
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
- apiGroups:
  - coredump.k8s.io
  resources:
  - coredumps
  - coredumpquotas
  verbs:
  - get
  - list
  - create
  - patch
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 'system:coredump-detector'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredump-detector
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:kube-system:default
